server:
    port: 8090

spring:
    application:
        name: websocket-service
    devtools:
        restart:
            enabled: false
    activemq:
        broker-url: tcp://localhost:61616
        user: artemis
        password: artemis
        
logging:
    level:
        root: INFO
        org.springframework.web: DEBUG
    file:
        name: logs/application.log
    pattern:
        console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){yellow} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n%clr(%n){faint}"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    logback:
        rollingpolicy:
          max-file-size: 10MB
          total-size-cap: 1GB
          max-history: 30

jms:
    topic:
        price-info-free: ${PRICE_INFO_TOPIC_FREE:price.info.free}
        price-info-premium: ${PRICE_INFO_TOPIC_PREMIUM:price.info.premium}

