version: "3.1"
services:
  artemis:
    image: apache/activemq-artemis:latest-alpine
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
    container_name: Artemis
    networks:
      - messaging_net

networks:
  messaging_net:
    driver: bridge
  